### PR TITLE
Multi-folder & Folders outside workspace

### PR DESCRIPTION
**Pull request by reesemclean**

### CODE REVIEW

**Comment by reesemclean** [comment]
I would like to display these this selection so that the template name was upfront but that is something that can be improved upon later:

screen shot 2018-04-30 at 10 38 49 pm

**Comment by ReiMcCl** [comment]
In one of my recent commits I implemented aliasing through structuring the templatePaths as an object and using the key to precede the component,, would that be sufficient in this instance?

https://github.com/ReiMcCl/blueprint/commit/a7139b1439ba0c2fc371db013be24f52b882f25f

For example, if you have the below object:

`templatePaths: {
    "Alias": "blueprint-template"
}`

The template would appear as Alias : [TEMPLATE NAME].

**Comment by reesemclean** [comment]
Yes something like that would work but would require more upfront work for someone to setup.

I wonder if the menu can just be displayed like:

{TEMPLATE_NAME} ({PATH_TO_TEMPLATE})

If there is a way have PATH_TO_TEMPLATE a lighter color than the template name to really emphasize the template name since I think the template name is most important part.

Showing the path needs to be there to be able to figure out where it came from and to differentiate two templates with similar names.

Doing it like that makes it so the user doesn’t have to set it up.

Further, there is the manifest.json that could possibly be used to add a title to be shown in the menu (manifest is optional so someone could set it up if they wanted).

**Comment by reesemclean** [comment]
Created https://github.com/reesemclean/blueprint/issues/44 to discuss possible solutions.

**Pull request merged**
